#!/usr/bin/env node

import File from "fs-extra";
import packageJSON from "../package";

const KEYS = ["author", "dependencies", "description", "main", "name", "version"],
      DATA = KEYS.reduce((object, key) => {
        return Object.assign(object, { [key]: packageJSON[key] });
      }, {});

try {
  File.mkdirSync("./build");
} catch (error) {
  if (error.code !== "EEXIST") {
    throw error;
  }
}

File.removeSync("./build");
File.removeSync("./release");

File.copySync("./application/images", "./build/images");
File.writeFileSync("./build/index.html", File.readFileSync("./application/index.html"));
File.writeFileSync("./build/package.json", JSON.stringify(DATA));
